version: '3.8'
services:
  web:
    build: .
    ports:
      - '8080'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/ktaxes'
      PORT: '8080'
      POSTGRES_USER: 'adminTax'
      POSTGRES_PASSWORD: 'admin!'


